// U-card terrain map — локальные лейблы (A..Z, AA..GG × 1..10).
// Собрано вручную с помощью tag-mode + auto-extract из terrainPixels.json.
export const hexMapU = {
  AA1:  ['forest'],
  AA2:  ['dirtRoad'],
  AA5:  ['forest'],
  AA6:  ['forest'],
  AA8:  ['forest'],
  AA10: ['forest'],
  AB1:  ['forest'],
  AB2:  ['forest'],
  AB3:  ['dirtRoad'],
  AB7:  ['brush'],
  AB9:  ['forest'],
  AC1:  ['forest'],
  AC3:  ['dirtRoad'],
  AC4:  ['forest'],
  AC7:  ['brush'],
  AC8:  ['brush'],
  AC9:  ['forest'],
  AD1:  ['forest'],
  AD2:  ['forest'],
  AD3:  ['forest'],
  AD4:  ['Woods-Road'],
  AD5:  ['forest'],
  AD8:  ['brush'],
  AD9:  ['forest'],
  AD10: ['brush'],
  AE1:  ['forest'],
  AE2:  ['forest'],
  AE3:  ['forest'],
  AE4:  ['Woods-Road'],
  AE5:  ['forest'],
  AE6:  ['brush'],
  AE7:  ['brush'],
  AE8:  ['brush'],
  AE9:  ['forest'],
  AF3:  ['forest'],
  AF4:  ['forest'],
  AF5:  ['Woods-Road'],
  AF9:  ['forest'],
  AG5:  ['dirtRoad'],
  AG6:  ['woodenBuilding'],
  B4:   ['forest'],
  B5:   ['dirtRoad'],
  B6:   ['dirtRoad'],
  B7:   ['forest'],
  C5:   ['dirtRoad'],
  C7:   ['orchard'],
  D1:   ['forest'],
  D2:   ['forest'],
  D3:   ['forest'],
  D5:   ['dirtRoad'],
  D6:   ['dirtRoad'],
  D7:   ['orchard'],
  D9:   ['crestLine'],
  D10:  ['crestLine'],
  E1:   ['forest'],
  E2:   ['brush'],
  E4:   ['dirtRoad'],
  E5:   ['crestLine'],
  E6:   ['dirtRoad'],
  E7:   ['woodenBuilding'],
  E8:   ['crestLine'],
  E9:   ['crestLine'],
  F1:   ['brush'],
  F2:   ['brush'],
  F4:   ['dirtRoad'],
  F5:   ['orchard', 'crestLine'],
  F6:   ['woodenBuilding', 'crestLine'],
  F7:   ['dirtRoad'],
  F8:   ['orchard', 'crestLine'],
  F9:   ['hill'],
  F10:  ['crestLine'],
  G2:   ['woodenBuilding'],
  G3:   ['dirtRoad'],
  G4:   ['woodenBuilding', 'crestLine'],
  G5:   ['orchard', 'hill'],
  G6:   ['crestLine'],
  G7:   ['dirtRoad'],
  G8:   ['crestLine'],
  G9:   ['crestLine'],
  H2:   ['woodenBuilding'],
  H3:   ['dirtRoad'],
  H4:   ['crestLine'],
  H5:   ['orchard', 'hill'],
  H6:   ['woodenBuilding', 'crestLine'],
  H7:   ['dirtRoad'],
  H8:   ['dirtRoad'],
  H9:   ['woodenBuilding'],
  H10:  ['crestLine'],
  I1:   ['woodenBuilding'],
  I2:   ['dirtRoad'],
  I3:   ['woodenBuilding', 'crestLine'],
  I4:   ['crestLine'],
  I5:   ['woodenBuilding', 'crestLine'],
  I6:   ['dirtRoad'],
  I7:   ['stoneBuilding'],
  I8:   ['dirtRoad'],
  I9:   ['crestLine'],
  I10:  ['forest'],
  J1:   ['dirtRoad'],
  J2:   ['dirtRoad'],
  J3:   ['stoneBuilding'],
  J4:   ['stoneBuilding'],
  J5:   ['stoneBuilding'],
  J6:   ['dirtRoad'],
  J7:   ['stoneBuilding'],
  J8:   ['stoneBuilding'],
  J9:   ['dirtRoad'],
  J10:  ['dirtRoad'],
  K1:   ['stoneBuilding'],
  K2:   ['dirtRoad'],
  K3:   ['dirtRoad'],
  K4:   ['dirtRoad'],
  K5:   ['orchard', 'pavedRoad'],
  K6:   ['orchard', 'pavedRoad'],
  K7:   ['orchard', 'pavedRoad'],
  K8:   ['orchard', 'pavedRoad'],
  K10:  ['forest'],
  L2:   ['stoneBuilding'],
  L3:   ['dirtRoad'],
  L4:   ['stoneBuilding'],
  L5:   ['stoneBuilding'],
  L6:   ['dirtRoad'],
  L7:   ['stoneBuilding'],
  L8:   ['orchard', 'pavedRoad'],
  M2:   ['dirtRoad'],
  M3:   ['stoneBuilding'],
  M5:   ['stoneBuilding'],
  M6:   ['dirtRoad'],
  M7:   ['dirtRoad'],
  M8:   ['stoneBuilding'],
  M10:  ['forest'],
  N2:   ['dirtRoad'],
  N3:   ['stoneBuilding'],
  N5:   ['stoneBuilding'],
  N6:   ['orchard', 'pavedRoad'],
  N7:   ['stoneBuilding'],
  N8:   ['dirtRoad'],
  N9:   ['stoneBuilding'],
  O1:   ['forest'],
  O2:   ['dirtRoad'],
  O3:   ['stoneBuilding'],
  O4:   ['stoneBuilding'],
  O5:   ['orchard', 'pavedRoad'],
  O6:   ['stoneBuilding'],
  O7:   ['stoneBuilding'],
  O8:   ['dirtRoad'],
  O10:  ['forest'],
  P1:   ['woodenBuilding'],
  P2:   ['dirtRoad'],
  P5:   ['orchard', 'pavedRoad'],
  P8:   ['stoneBuilding'],
  P9:   ['dirtRoad'],
  Q1:   ['dirtRoad'],
  Q2:   ['stoneBuilding'],
  Q3:   ['stoneBuilding'],
  Q4:   ['orchard', 'pavedRoad'],
  Q5:   ['woodenBuilding'],
  Q7:   ['woodenBuilding'],
  Q8:   ['dirtRoad'],
  R1:   ['dirtRoad'],
  R2:   ['orchard', 'pavedRoad'],
  R3:   ['orchard', 'pavedRoad'],
  R4:   ['orchard', 'pavedRoad'],
  R8:   ['dirtRoad'],
  R9:   ['dirtRoad'],
  R10:  ['dirtRoad'],
  S1:   ['woodenBuilding'],
  S3:   ['woodenBuilding'],
  S7:   ['dirtRoad'],
  T3:   ['forest'],
  T8:   ['dirtRoad'],
  U2:   ['forest'],
  U3:   ['forest'],
  U4:   ['forest'],
  U8:   ['dirtRoad'],
  U10:  ['forest'],
  V3:   ['forest'],
  V4:   ['forest'],
  V5:   ['forest'],
  V8:   ['dirtRoad'],
  W4:   ['forest'],
  W7:   ['dirtRoad'],
  W8:   ['woodenBuilding'],
  W10:  ['forest'],
  X8:   ['dirtRoad'],
  Y4:   ['forest'],
  Y5:   ['forest'],
  Y6:   ['forest'],
  Y8:   ['dirtRoad'],
  Y10:  ['forest'],
  Z1:   ['dirtRoad'],
  Z2:   ['dirtRoad'],
  Z3:   ['woodenBuilding'],
  Z4:   ['forest'],
  Z5:   ['forest'],
  Z6:   ['forest'],
  Z7:   ['forest'],
  Z8:   ['forest'],
  Z9:   ['dirtRoad'],
  Z10:  ['dirtRoad'],
};
