export const scenarios = {
  A: {
    hexmapModule: () => import('./hexmapBaked.js').then(m => m.hexMap),
    pixelsUrl:    './terrainPixels.json',
    cardVisuals: [
      { // V — правая карта, rotation 180
        images: [
          './graf/base_layer.png',
          './graf/terrain_inside_1.png',
        ],
        overlayImages: [
          './graf/woods_outline.png',
          './graf/buildings_outline.png',
          './graf/hills_outline_1.png',
          './graf/orchard_outline_1.png',
          './graf/brush_outline.png',
        ],
        roadImage: './graf/roads_outline.png',
        x: 0, y: 0, width: 1800, height: 645, rotation: 180,
      },
      { // U — левая карта, rotation 0
        images: [
          './graf/bdu_base_layer.png',
          './graf/bdu_terrain_inside.png',
        ],
        overlayImages: [
          './graf/bdu_woods_outline.png',
          './graf/bdu_buildings_outline.png',
          './graf/bdu_hills_outline.png',
          './graf/bdu_orchard_outline.png',
          './graf/bdu_brush_outline.png',
        ],
        roadImage: './graf/bdu_roads_outline_1.png',
        x: -1800, y: 0, width: 1800, height: 645, rotation: 0,
      },
    ],
    units: [
      // --- German (defender) ---
      { templateId: 'ge_467', id: 'unit_01', side: 'defender', hex: { col: 38, row: 9 } },
      { templateId: 'ge_467', id: 'unit_02', side: 'defender', hex: { col: 38, row: 9 } },
      { templateId: 'ge_467', id: 'unit_03', side: 'defender', hex: { col: 38, row: 9 } },
      { templateId: 'ge_447', id: 'unit_04', side: 'defender', hex: { col: 29, row: 4 } },
      { templateId: 'ge_447', id: 'unit_05', side: 'defender', hex: { col: 29, row: 4 } },
      { templateId: 'ge_447', id: 'unit_06', side: 'defender', hex: { col: 29, row: 4 } },
      { templateId: 'ge_447', id: 'unit_07', side: 'defender', hex: { col: 39, row: 3 } },
      { templateId: 'ge_447', id: 'unit_08', side: 'defender', hex: { col: 39, row: 3 } },
      { templateId: 'ge_447', id: 'unit_09', side: 'defender', hex: { col: 39, row: 3 } },
      { templateId: 'ge_L81', id: 'unit_L81', side: 'defender', hex: { col: 38, row: 9 } },
      { templateId: 'ge_L80', id: 'unit_L80', side: 'defender', hex: { col: 29, row: 4 } },
      { templateId: 'ge_L70', id: 'unit_L70', side: 'defender', hex: { col: 39, row: 3 } },
      { templateId: 'ge_MMG', id: 'geMMG_vG8',   side: 'defender', possessorId: 'unit_01' },
      { templateId: 'ge_LMG', id: 'geLMG_vH2',   side: 'defender', possessorId: 'unit_07' },
      { templateId: 'ge_LMG', id: 'geLMG_uAC4',  side: 'defender', possessorId: 'unit_04' },
      { templateId: 'ge_LMG', id: 'geLMG_vH2_2', side: 'defender', possessorId: 'unit_08' },
      // --- Russian (attacker) ---
      { templateId: 'so_426', id: 'unit_ru5', side: 'attacker', hex: { col: 25, row: 6 } },
      { templateId: 'so_426', id: 'unit_ru6', side: 'attacker', hex: { col: 25, row: 6 } },
      { templateId: 'so_426', id: 'unit_ru7', side: 'attacker', hex: { col: 25, row: 6 } },
      { templateId: 'so_426', id: 'unit_ru8', side: 'attacker', hex: { col: 24, row: 5 } },
      { templateId: 'so_426', id: 'unit_ru9', side: 'attacker', hex: { col: 24, row: 5 } },
      { templateId: 'so_426', id: 'unit_ru10', side: 'attacker', hex: { col: 24, row: 5 } },
      { templateId: 'so_426', id: 'unit_ru11', side: 'attacker', hex: { col: 24, row: 5 } },
      { templateId: 'so_L81', id: 'unit_ruL81', side: 'attacker', hex: { col: 25, row: 6 } },
      // --- American (attacker) ---
      { templateId: 'am_667', id: 'unit_am1', side: 'attacker', hex: { col: 48, row: 5 } },
      { templateId: 'am_667', id: 'unit_am2', side: 'attacker', hex: { col: 48, row: 5 } },
      { templateId: 'am_667', id: 'unit_am3', side: 'attacker', hex: { col: 48, row: 5 } },
      { templateId: 'am_667', id: 'unit_am4', side: 'attacker', hex: { col: 48, row: 4 } },
      { templateId: 'am_667', id: 'unit_am5', side: 'attacker', hex: { col: 48, row: 4 } },
      { templateId: 'am_667', id: 'unit_am6', side: 'attacker', hex: { col: 48, row: 4 } },
      { templateId: 'am_536', id: 'unit_am7', side: 'attacker', hex: { col: 48, row: 11 } },
      { templateId: 'am_536', id: 'unit_am8', side: 'attacker', hex: { col: 48, row: 11 } },
      { templateId: 'am_536', id: 'unit_am9', side: 'attacker', hex: { col: 48, row: 11 } },
      { templateId: 'am_536', id: 'unit_am10', side: 'attacker', hex: { col: 48, row: 10 } },
      { templateId: 'am_536', id: 'unit_am11', side: 'attacker', hex: { col: 48, row: 10 } },
      { templateId: 'am_L92', id: 'unit_amL92', side: 'attacker', hex: { col: 48, row: 5 } },
      { templateId: 'am_L81', id: 'unit_amL81', side: 'attacker', hex: { col: 48, row: 11 } },
      { templateId: 'am_MMG', id: 'amMMG_vQ4',  side: 'attacker', possessorId: 'unit_am1' },
    ],
    orchardInSeason: true,
    activeRole: 'attacker',
    initialCamera: { x: 750, y: 0 },
    roadsUrl: './roadPixels.json',
  },

  B: {
    hexmapModule: () => import('./hexmapU_rot.js').then(m => m.hexMapU_rot),
    pixelsUrl:    './terrainPixelsU_rot.json',
    cardVisuals: [
      { // U повёрнутая — та же PNG, rotation 180
        images: [
          './graf/bdu_base_layer.png',
          './graf/bdu_terrain_inside.png',
        ],
        overlayImages: [
          './graf/bdu_woods_outline.png',
          './graf/bdu_buildings_outline.png',
          './graf/bdu_hills_outline.png',
          './graf/bdu_orchard_outline.png',
          './graf/bdu_brush_outline.png',
        ],
        roadImage: './graf/bdu_roads_outline_1.png',
        x: -1800, y: 0, width: 1800, height: 645, rotation: 180,
      },
    ],
    units: [
      // --- German (defender) в 17-6 ---
      { templateId: 'ge_467', id: 'unit_b1', side: 'defender', hex: { col: 17, row: 6 } },
      { templateId: 'ge_467', id: 'unit_b2', side: 'defender', hex: { col: 17, row: 6 } },
      { templateId: 'ge_467', id: 'unit_b3', side: 'defender', hex: { col: 17, row: 6 } },
      { templateId: 'ge_L80', id: 'unit_bL80', side: 'defender', hex: { col: 17, row: 6 } },
      { templateId: 'ge_LMG', id: 'geLMG_B17_6', side: 'defender', possessorId: 'unit_b1' },
      // --- Russian (attacker) в 13-7 ---
      { templateId: 'so_458', id: 'unit_b4', side: 'attacker', hex: { col: 13, row: 7 } },
      { templateId: 'so_458', id: 'unit_b5', side: 'attacker', hex: { col: 13, row: 7 } },
      { templateId: 'so_458', id: 'unit_b6', side: 'attacker', hex: { col: 13, row: 7 } },
      { templateId: 'so_L61', id: 'unit_bL61', side: 'attacker', hex: { col: 13, row: 7 } },
      { templateId: 'ru_LMG', id: 'ruLMG_B13_7', side: 'attacker', possessorId: 'unit_b4' },
      { templateId: 'ge_467', id: 'unit_b9', side: 'defender', hex: { col: 19, row: 6 } },
    ],
    orchardInSeason: false,
    activeRole: 'attacker',
    initialCamera: { x: 1800, y: 0 },
    roadsUrl: './roadPixelsU_rot.json',
  },
};
